import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navigate from "@/components/Navigate";
import {main} from './page.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={main}>
      <Navigate />
      {children}
      <Footer />
      </body>
    </html>
  );
}
